/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'background-color': 'var(--background-color)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'primary-cta': 'var(--primary-cta)',
        'card-background': 'var(--card-background)',
        'navbar-bg': 'var(--navbar-bg)',
        'section-bg': 'var(--section-bg)',
        'accent-light': 'var(--accent-light)',
        'border-color': 'var(--border-color)',
      },
      animation: {
        'float': 'float 3s ease-in-out infinite',
        'gentle-glow': 'gentle-glow 3s ease-in-out infinite',
        'slide-in-right': 'slide-in-right 0.6s ease-out forwards',
        'rainbow': 'rainbow 3s linear infinite',
        'bounce-gentle': 'bounce-gentle 2s ease-in-out infinite',
        'shimmer': 'shimmer 2s ease-in-out infinite',
        'scale-in': 'scale-in 0.5s ease-out forwards',
        'slide-up': 'slide-up 0.4s ease-out forwards',
        'floating-shapes': 'floating-shapes 6s ease-in-out infinite',
        'pulse-border': 'pulse-border 3s ease-in-out infinite',
        'wave': 'wave 3s linear infinite',
        'bounce-soft': 'bounce-soft 3s ease-in-out infinite',
        'rotate-slow': 'rotate-slow 20s linear infinite',
        'gradient-shift': 'gradient-shift 4s ease infinite',
        'sparkle': 'sparkle 2s ease-in-out infinite',
        'shooting-star': 'shooting-star 3s linear infinite',
        'constellation': 'constellation 4s ease-in-out infinite',
        'cosmic-drift': 'cosmic-drift 6s ease-in-out infinite',
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
        'twinkle': 'twinkle 3s ease-in-out infinite',
        'orbit': 'orbit 10s linear infinite',
        'drift': 'drift 8s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
